apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: 'version.gradle'

android {
    namespace 'com.kaltura.playkit.plugin.broadpeak'
    compileSdk 35
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lintOptions {
        abortOnError false
    }
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionName libVersion
        buildConfigField("String","VERSION_NAME","\"${libVersion}\"")
    }
    buildFeatures {
        buildConfig true
    }
    publishing {
        publishing {
            singleVariant('release') {
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    
    // TODO: when tvplayer is released, replace this.
    api 'com.kaltura.player:tvplayer:5.0.5-rc1-simid'
    //api project(":tvplayer")
    //api 'tv.broadpeak.smartlib:smartlib-kaltura:04.07.01.4334a05'
    api 'tv.broadpeak.smartlib:smartlib-kaltura:05.02.03.730dca7'
    api 'tv.broadpeak.smartlib:smartlib-media3:05.02.03.730dca7'
}

repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}

if (!ext.libVersion.contains('dev')) {
    apply from: './gradle-mvn-push.gradle'
} else {
    apply from: './gradle-mvn-local.gradle'
}

